<?php

namespace FondOfSpryker\Yves\GoogleTagManageProductConnector;

use Spryker\Yves\Kernel\AbstractBundleDependencyProvider;
use Spryker\Yves\Kernel\Container;

class GoogleTagManageProductConnectorDependencyProvider extends AbstractBundleDependencyProvider
{
    /**
     * @param \Spryker\Yves\Kernel\Container $container
     *
     * @return Spryker\Yves\Kernel\Container
     */
    public function provideDependencies(Container $container): Container
    {
        return parent::provideDependencies($container); // TODO: Change the autogenerated stub
    }
}
